import argparse
import os

parser = argparse.ArgumentParser()

parser.add_argument('file_pattern', type=str,
                    help='The pattern for the dump files (e.g. "dump_*.liggghts")')

args = parser.parse_args()

files = os.listdir('.')
sim_files = []
for file in files:
    s = args.file_pattern.split('*')
    if file.startswith(s[0]) and file.endswith(s[1]):
        sim_files.append(file)

for file in sim_files:
    with open(file, 'r') as f:
        file_list = []
        sub_file_lines = []
        s = args.file_pattern.split('*')
        file_timestep = int(file[len(s[0]):-len(s[1])])
        lines = f.readlines()

        points = []
        id = []
        type = []
        vel = []
        radius = []
        density = []

        point_data = lines[9:]
        
        header = '# vtk DataFile Version 2.0\nGenerated by Matt\nASCII\nDATASET POLYDATA\nPOINTS ' + str(len(point_data)) + ' float\n'

        if point_data:
            if len(point_data[-1]) < 3:
                point_data = point_data[:-1]

        for line in point_data:
            split_data = line.split(' ')
            points.append([split_data[2], split_data[3], split_data[4]])
            id.append(split_data[0])
            type.append(split_data[1])
            vel.append([split_data[5], split_data[6], split_data[7]])
            radius.append(split_data[8])
            density.append(split_data[9].strip())
        
        sub_file_lines.append(header)

        for point in points:
            sub_file_lines.append(' '.join(point) + '\n')
        
        sub_file_lines.append('VERTICES ' + str(len(point_data)) + ' ' + str(len(point_data) * 2) + '\n')

        for i in range(len(point_data)):
            sub_file_lines.append(' '.join((type[i], str(i))) + '\n')
        
        sub_file_lines.append('POINT_DATA ' + str(len(point_data)) + '\n')
        
        if(vel):
            sub_file_lines.append('VECTORS v float\n')

            for v in vel:
                sub_file_lines.append(' '.join(v) + '\n')
            
            sub_file_lines.append('SCALARS radius float 1\n LOOKUP_TABLE default\n')

            for r in radius:
                sub_file_lines.append(r + '\n')
            
            sub_file_lines.append('SCALARS type float 1\nLOOKUP_TABLE default\n')

            for t in type:
                sub_file_lines.append(str(float(t)) + '\n')
            
            sub_file_lines.append('SCALARS id float 1\nLOOKUP_TABLE default\n')

            for i in id:
                sub_file_lines.append(str(float(i)) + '\n')

            sub_file_lines.append('SCALARS density float 1\nLOOKUP_TABLE default\n')

            for d in density:
                sub_file_lines.append(str(float(d)) + '\n')
        
        outfile = open(s[0] + str(file_timestep).zfill(4) + '.vtk', 'w')
        outfile.writelines(sub_file_lines)
        outfile.close()